apiVersion: v1
kind: Service
metadata:
  name: vanus-gateway
  namespace: vanus-default
spec:
  selector:
    app: vanus-gateway
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      # nodePort: 30001
      name: proxy
    - port: 8081
      targetPort: 8081
      # nodePort: 30002
      name: cloudevents
---
apiVersion: v1
data:
  gateway.yaml: |-
    port: 8080
    sink_port: 8082
    auth: 
      disable: true
    controllers:
      - vanus-controller-0.vanus-controller:2048
      - vanus-controller-1.vanus-controller:2048
kind: ConfigMap
metadata:
  name: config-gateway
  namespace: vanus-default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vanus-gateway
  name: vanus-gateway
  namespace: vanus-default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vanus-gateway
  template:
    metadata:
      annotations:
        vanus.dev/metrics.port: "2112"
      labels:
        app: vanus-gateway
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: core.vanus.ai/dedicated
                operator: In
                values:
                - core
      tolerations:
      - key: "core.vanus.ai/dedicated"
        operator: "Equal"
        value: "core"
        effect: "NoSchedule"
      containers:
      - env:
        - name: VANUS_LOG_LEVEL
          value: INFO
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: public.ecr.aws/vanus/gateway:2adbb0f
        imagePullPolicy: IfNotPresent
        name: gateway
        ports:
        - containerPort: 8080
          name: proxy
        - containerPort: 8081
          name: cloudevents
        - containerPort: 8082
          name: sinkproxy
        volumeMounts:
        - mountPath: /vanus/config
          name: config-gateway
      volumes:
      - configMap:
          name: config-gateway
        name: config-gateway
