apiVersion: v1
kind: ConfigMap
metadata:
  name: config-controller
  namespace: vanus
data:
  controller.yaml: |-
    name: ${POD_NAME}
    ip: ${POD_IP}
    port: 2048
    etcd:
      - vanus-controller-0.vanus-controller:2379
      - vanus-controller-1.vanus-controller:2379
      - vanus-controller-2.vanus-controller:2379
    data_dir: /data
    replicas: 3
    metadata:
      key_prefix: /vanus
    topology:
      vanus-controller-0: vanus-controller-0.vanus-controller.vanus.svc:2048
      vanus-controller-1: vanus-controller-1.vanus-controller.vanus.svc:2048
      vanus-controller-2: vanus-controller-2.vanus-controller.vanus.svc:2048
    embed_etcd:
      # relative path to ${data_dir} above
      data_dir: etcd/data
      listen_client_addr: 0.0.0.0:2379
      listen_peer_addr: 0.0.0.0:2380
      advertise_client_addr: ${POD_NAME}.vanus-controller:2379
      advertise_peer_addr: ${POD_NAME}.vanus-controller:2380
      clusters:
        - vanus-controller-0=http://vanus-controller-0.vanus-controller:2380
        - vanus-controller-1=http://vanus-controller-1.vanus-controller:2380
        - vanus-controller-2=http://vanus-controller-2.vanus-controller:2380
---
apiVersion: v1
kind: Service
metadata:
  name: vanus-controller
  namespace: vanus
spec:
  selector:
    app: vanus-controller
  clusterIP: None
  ports:
    - port: 2048
      name: vanus-controller
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vanus-controller
  namespace: vanus
  labels:
    app: vanus-controller
spec:
  selector:
    matchLabels:
      app: vanus-controller
  replicas: 3
  serviceName: vanus-controller
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: vanus-controller
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      labels:
        app: vanus-controller
      annotations:
        vanus.dev/metrics.port: "2112"
    spec:
      containers:
        - name: controller
          image: public.ecr.aws/vanus/controller:v0.2.0
          imagePullPolicy: IfNotPresent
  #          livenessProbe:
  #            grpc:
  #              port: 2048
  #            failureThreshold: 10
  #            periodSeconds: 30
          ports:
            - name: grpc
              containerPort: 2048
            - name: etcd-client
              containerPort: 2379
            - name: etcd-peer
              containerPort: 2380
            - name: metrics
              containerPort: 2112
          env:
            - name: VANUS_LOG_LEVEL
              value: DEBUG
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: config-controller
              mountPath: /vanus/config
            - name: data
              mountPath: /data
      volumes:
        - name: config-controller
          configMap:
            name: config-controller