apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanus-vsctl
  namespace: vanus
  labels:
    app: vanus-vsctl
spec:
  selector:
    matchLabels:
      app: vanus-vsctl
  replicas: 1
  template:
    metadata:
      labels:
        app: vanus-vsctl
    spec:
      containers:
        - name: vsctl
          image: public.ecr.aws/vanus/vsctl:5952928
          imagePullPolicy: Always
          command: ['sh', '-c', 'sleep 360000']