apiVersion: v1
data:
  store.yaml: |-
    port: 11811
    ip: ${POD_IP}
    # host: ${POD_NAME}.vanus-store.vanus-standby.svc.cluster.local
    controllers:
      - vanus-controller-0.vanus-controller:2048
      - vanus-controller-1.vanus-controller:2048
    volume:
      id: ${VOLUME_ID}
      dir: /data
      capacity: 1073741824
    meta_store:
      wal:
        io:
          engine: psync
    offset_store:
      wal:
        io:
          engine: psync
    raft:
      wal:
        block_size: 16384
        io:
          engine: psync
          parallel: 16
    vsb:
      flush_batch_size: 16384
      io:
        engine: psync
        parallel: 16
    observability:
      metrics:
        enable: true
      tracing:
        enable: false
kind: ConfigMap
metadata:
  name: config-store
  namespace: vanus-standby
---
apiVersion: v1
kind: Service
metadata:
  name: vanus-store
  namespace: vanus-standby
spec:
  clusterIP: None
  selector:
    app: vanus-store
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: vanus-store
  name: vanus-store
  namespace: vanus-standby
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vanus-store
  serviceName: vanus-store
  template:
    metadata:
      annotations:
        vanus.dev/metrics.port: "2112"
      labels:
        app: vanus-store
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: core.vanus.ai/dedicated
                operator: In
                values:
                - core
      tolerations:
      - key: "core.vanus.ai/dedicated"
        operator: "Equal"
        value: "core"
        effect: "NoSchedule"
      containers:
      - command:
        - /bin/sh
        - -c
        - VOLUME_ID=${HOSTNAME##*-} /vanus/bin/store
        env:
        - name: VANUS_LOG_LEVEL
          value: INFO
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: public.ecr.aws/vanus/store:d03f5ed
        imagePullPolicy: IfNotPresent
        name: store
        ports:
        - containerPort: 11811
          name: grpc
        volumeMounts:
        - mountPath: /vanus/config
          name: config-store
        - mountPath: /data
          name: data
      volumes:
      - configMap:
          name: config-store
        name: config-store
  volumeClaimTemplates:
  - metadata:
      labels:
        app: vanus-store
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      # storageClassName: gp2
      volumeMode: Filesystem
