name: "test-1"
ip: "127.0.0.1"
port: 2048
grpc_reflection_enable: true
etcd:
  - "127.0.0.1:2379"
data_dir: "/tmp/data/vanus"
metadata:
  key_prefix: "/wenfeng"
topology:
  test-1: 127.0.0.1:2048
embed_etcd:
  # relative path to ${data_dir} above
  data_dir: "etcd/node1"
  client_addr: "127.0.0.1:2379"
  peer_addr: "127.0.0.1:2380"
  clusters:
    - "test-1=http://127.0.0.1:2380"
