apiVersion: v1
data:
  root.yaml: |-
    node_id: ${NODE_ID}
    name: ${POD_NAME}
    ip: ${POD_IP}
    port: 2021
    observability:
      metrics:
        enable: true
      tracing:
        enable: false
        # OpenTelemetry Collector endpoint, https://opentelemetry.io/docs/collector/getting-started/
        otel_collector: http://127.0.0.1:4318
    cluster:
      component_name: root-controller
      lease_duration_in_sec: 15
      etcd:
        - vanus-etcd-0.vanus-etcd:2379
        - vanus-etcd-1.vanus-etcd:2379
        - vanus-etcd-2.vanus-etcd:2379
      topology:
        vanus-root-controller-0: vanus-root-controller-0.vanus-root-controller.vanus.svc:2021
        vanus-root-controller-1: vanus-root-controller-1.vanus-root-controller.vanus.svc:2021
kind: ConfigMap
metadata:
  name: config-root-controller
  namespace: vanus
---
apiVersion: v1
kind: Service
metadata:
  name: vanus-root-controller
  namespace: vanus
spec:
  clusterIP: None
  ports:
  - name: vanus-root-controller
    port: 2021
  selector:
    app: vanus-root-controller
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: vanus-root-controller
  name: vanus-root-controller
  namespace: vanus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vanus-root-controller
  serviceName: vanus-root-controller
  template:
    metadata:
      annotations:
        vanus.dev/metrics.port: "2112"
      labels:
        app: vanus-root-controller
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - NODE_ID=${HOSTNAME##*-} /vanus/bin/root-controller
        env:
        - name: VANUS_LOG_LEVEL
          value: INFO
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: public.ecr.aws/vanus/root-controller:v0.8.0
        imagePullPolicy: IfNotPresent
        name: controller
        ports:
        - containerPort: 2021
          name: grpc
        - containerPort: 2112
          name: metrics
        volumeMounts:
        - mountPath: /vanus/config
          name: config-root-controller
      volumes:
      - configMap:
          name: config-root-controller
        name: config-root-controller
