kind: ConfigMap
metadata:
  name: config-controller
  namespace: vanus
apiVersion: v1
data:
  controller.yaml: |-
    node_id: ${NODE_ID}
    name: ${POD_NAME}
    ip: ${POD_IP}
    port: 2048
    etcd:
      - vanus-etcd-0.vanus-etcd:2379
      - vanus-etcd-1.vanus-etcd:2379
      - vanus-etcd-2.vanus-etcd:2379
    data_dir: /data
    segment_capacity: 268435456
    replicas: 3
    metadata:
      key_prefix: /vanus
    leader_election:
      lease_duration: 15
    topology:
      vanus-controller-0: vanus-controller-0.vanus-controller.vanus.svc:2048
      vanus-controller-1: vanus-controller-1.vanus-controller.vanus.svc:2048
      vanus-controller-2: vanus-controller-2.vanus-controller.vanus.svc:2048
    observability:
      metrics:
        enable: true
      tracing:
        enable: false
---
apiVersion: v1
kind: Service
metadata:
  name: vanus-controller
  namespace: vanus
spec:
  clusterIP: None
  ports:
    - name: vanus-controller
      port: 2048
  selector:
    app: vanus-controller
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: vanus-controller
  name: vanus-controller
  namespace: vanus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vanus-controller
  serviceName: vanus-controller
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
      labels:
        app: vanus-controller
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - NODE_ID=${HOSTNAME##*-} /vanus/bin/controller
          env:
            - name: VANUS_LOG_LEVEL
              value: DEBUG
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: public.ecr.aws/vanus/controller:02c5b59
          imagePullPolicy: IfNotPresent
          name: controller
          ports:
            - containerPort: 2048
              name: grpc
            - containerPort: 2112
              protocol: TCP
              name: metrics
          volumeMounts:
            - mountPath: /vanus/config
              name: config-controller
        - name: node-exporter
          image: prom/node-exporter
          args:
            - --no-collector.wifi
            - --no-collector.hwmon
            - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)
            - --collector.netclass.ignored-devices=^(veth.*)$
          ports:
            - containerPort: 9100
              protocol: TCP
              name: metrics
          resources:
            limits:
              cpu: 250m
              memory: 180Mi
            requests:
              cpu: 102m
              memory: 180Mi
      volumes:
        - configMap:
            name: config-controller
          name: config-controller