name: codecov
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read-
jobs:
  codecov:
    strategy:
      matrix:
        go-version: [ 1.17.x ]
        os: [ ubuntu-latest ]
    name: codecov
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v2
      - name: checkout-vanus
        uses: actions/checkout@v3
      - name: Generate coverage report
        timeout-minutes: 2
        run: |
          pwd && ls -alh && go test -failfast -race -coverprofile=coverage.txt -covermode=atomic -timeout 20s ./internal/...
      - uses: codecov/codecov-action@v2
        with:
          token: 931ae77e-a303-4e84-9c9f-33083aceaef2 # not required for public repos
          working-directory: vanus
          files: ./coverage.txt # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)