header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Linkall Inc.

  paths-ignore:
    - 'docs/'
    - 'bu'
    - '.gitignore'
    - '.gitattributes'
    - '.golangci.yml'
    - '.golangci_br.yml'
    - 'LICENSES/'
    - '**/*.md'
    - '**/*.json'
    - '**/*.test'
    - '**/*.result'
    - '**/*.example'
    - '.codecov.yml'
    - '**/go.mod'
    - '**/go.sum'
    - 'LICENSE'
    - '.github/'
    - 'parser/'
    - 'dumpling/'
  comment: on-failure